// import 'package:get/get.dart';

// class LocaleString extends Translations {
//   @override
//   Map<String, Map<String, String>> get keys => {
//         'en_US': {
//           "Pharmafast": "Pharmafast",
//           "Search for products or stores": "Search for products or stores",
//           "In the Spotlight": "In the Spotlight",
//           "Pharmafast we want you to explore":
//               "Pharmafast we want you to explore",
//         },
//         'hi_US': {
//           "Pharmafast": "फ़ार्माफ़ास्ट",
//           "Search for products or stores": "उत्पादों या दुकानों के लिए खोजें",
//           "In the Spotlight": "सुर्खियों में",
//           "Pharmafast we want you to explore":
//               "फ़ार्माफ़ास्ट हम चाहते हैं कि आप एक्सप्लोर करें",
//           "Shop now": "अभी खरीदें",
//           "No medical store available \nin your area.":
//               "आपके क्षेत्र में कोई मेडिकल स्टोर उपलब्ध नहीं है।",
//           "Your favorites": "आपका पसंदीदा",
//           "Pharmafast your love": "अपने प्यार को फ़ार्माफ़ास्ट करें",
//           "Pharmafast by category": "श्रेणी के द्वारा फ़ार्माफ़ास्ट",
//           "The milkman category  \nis unavailable in your area.":
//               "आपके क्षेत्र में दवा श्रेणी \n अनुपलब्ध है।",
//           "Top Medicine Stores": "शीर्ष दवा भंडार",
//           "Stores": "स्टोर",
//           "Products": "उत्पादों",
//           "Profile": "प्रोफ़ाइल",
//           "My Orders": "मेरे आदेश",
//           "Wallet": "बटुआ",
//           "Refer & Earn": "देखें और कमाएँ",
//           "Logout": "लॉग आउट",
//           "Are you sure you want to log out?":
//               "क्या आप लॉग आउट करना चाहते हैं?",
//           "Cancle": "कैंकल",
//           "Yes, Remove": "हाँ, हटाओ",
//           "Edit Profile": "प्रोफ़ाइल संपादित करें",
//           "Please enter full name": "कृपया पूरा नाम दर्ज करें",
//           "Full Name": "पूरा नाम",
//           "Number": "संख्या",
//           "Continue": "जारी रखना",
//           "Delete Account": "खाता हटा दो",
//           "Are you sure you want to delete account?":
//               "क्या आप वाकई खाता हटाना चाहते हैं?",
//           "My Prescription Orders": "मेरे नुस्खे के आदेश",
//           "My Wallet": "मेरा बटुआ",
//           "Language": "भाषा",
//           "Log out": "लॉग आउट",
//           "Earn": "कमाना",
//           "for Each\n Friend you refer":
//               "प्रत्येक\n मित्र के लिए जिसे आप संदर्भित करते हैं",
//           "Share the referral link with your friends":
//               "अपने दोस्तों के साथ रेफ़रल लिंक साझा करें",
//           "Friend get": "मित्र प्राप्त करें",
//           "on their first complete\ntransaction": "उनके पहले पूर्ण\nलेन-देन पर",
//           "You get": "आपको मिला",
//           "on your wallet": "आपके बटुए पर",
//           "Add Wallet": "बटुआ जोड़ें",
//           "Your current Balance": "आपका वर्तमान शेष",
//           "ADD": "जोड़ना",
//           "Select Payment Method": "भुगतान का तरीका चुनें",
//           "Add Your payment information": "अपनी भुगतान जानकारी जोड़ें",
//           "What number is written on card?": "कार्ड पर कौन सा नंबर लिखा है?",
//           "Number behind the card": "कार्ड के पीछे नंबर",
//           "Please fix the errors in red before submitting.":
//               "सबमिट करने से पहले कृपया लाल रंग की त्रुटियों को ठीक करें।",
//           "Payment card is valid": "भुगतान कार्ड मान्य है",
//           "Go & Add your Amount": "जाओ और अपनी राशि जोड़ें",
//           "ADD AMOUNT": "राशि जोड़ें",
//           "History": "इतिहास",
//           "Available Balance": "उपलब्ध शेष राशि",
//           "Overview": "अवलोकन",
//           "Photos": "तस्वीरें",
//           "Review": "समीक्षा",
//           "Orders and delivery": "आदेश और वितरण",
//           "Delivery acrosss India": "पूरे भारत में वितरण",
//           "Usually dispatches orders on the same day":
//               "आमतौर पर उसी दिन ऑर्डर डिस्पैच करते हैं",
//           "Delivery fee will apply": "वितरण शुल्क लागू होगा",
//           "All orders will be Delivered by":
//               "द्वारा सभी ऑर्डर डिलीवर किए जाएंगे",
//           "Cancellation policy": "रद्द करने की नीति",
//           "Store info": "जानकारी स्टोर करें",
//           "Sorry, there are no photos \n available to display at this time":
//               "क्षमा करें, इस समय प्रदर्शित करने के लिए कोई फोटो \n उपलब्ध नहीं है",
//           "Sorry, there are no reviews \nto display at this time":
//               "क्षमा करें, इस समय प्रदर्शित करने के लिए \nकोई समीक्षा नहीं है",
//           "Sorry, there are no photos \navailable to display at this time":
//               "क्षमा करें, इस समय प्रदर्शित करने के लिए कोई फोटो \nउपलब्ध नहीं है",
//           "Shop": "दुकान",
//           "About": "के बारे में",
//           "Prescription": "नुस्खा",
//           "Cart": "कार्ट",
//           "Upload Prescription ": "नुस्खा अपलोड करें ",
//           "and let usarrange your medicines for you":
//               "और हमें आपके लिए अपनी दवाओं की व्यवस्था करने दें",
//           "Get 15% off on medicines*": "दवाओं पर 15% की छूट*",
//           "How it works": "यह काम किस प्रकार करता है",
//           "Upload": "डालना",
//           "Recently added": "हाल ही में जोड़ा",
//           "iteam": "वस्तु",
//           "Add": "जोड़ना",
//           "All Products": "सभी प्रोडक्ट",
//           "Item": "वस्तु",
//           "Rx Required": "आरएक्स आवश्यक है",
//           "Exceeded the maximum quantity limit per order!":
//               "प्रति आदेश अधिकतम मात्रा सीमा को पार कर गया!",
//           "All coupons": "सभी कूपन",
//           "Enter Coupon Code": "परचा कूट दर्ज करें",
//           "APPLY": "आवेदन करना",
//           "Best Coupon": "सर्वश्रेष्ठ कूपन",
//           "Coupon Code: ": "कूपन कोड:",
//           "Apply coupons": "कूपन लागू करें",
//           "The Coupon is unavailable \n in your Store.":
//               "आपके स्टोर में कूपन उपलब्ध नहीं है।",
//           "We'll let you know when we\nget news for you":
//               "हम आपको बताएंगे कि जब हम आपके लिए समाचार प्राप्त करेंगे",
//           "Your Medicine in your Hand. Anytime - Anywhere":
//               "आपकी दवा आपके हाथ में। कभी भी कहीं भी",
//           "Set up your store, customise your storefront, and make it truly yours":
//               "अपना स्टोर सेट करें, अपने स्टोरफ्रंट को कस्टमाइज़ करें और इसे वास्तव में अपना बनाएं",
//           "One App for all users all over the city":
//               "पूरे शहर में सभी उपयोगकर्ताओं के लिए एक ऐप",
//           "Reduce your medical expenses by HALF":
//               "अपने चिकित्सा व्यय को आधा कम करें",
//           "Your safe delivery.Stay Connect & Healthy":
//               "आपका सुरक्षित प्रसव। कनेक्ट और स्वस्थ रहें",
//           "Buy Medicines Online – Delivered to Your Doorstep":
//               "दवाएं ऑनलाइन खरीदें - आपके दरवाजे पर डिलीवर की जाती हैं",
//           "Get Started": "शुरू हो जाओ",
//           "Skip": "छोडना",
//           "Next": "अगला",
//           "Your Cart": "आपकी गाड़ी",
//           "Required": "आवश्यक",
//           "The quantity cannot be modified as it has been prescribed by the doctors.":
//               "मात्रा को संशोधित नहीं किया जा सकता क्योंकि यह ऑक्टर द्वारा निर्धारित किया गया है।",
//           "Write instructions, gifting ideas etc..":
//               "निर्देश, उपहार देने के विचार आदि लिखें।",
//           "Prescription Require": "नुस्खे की आवश्यकता",
//           "your order contain": "आपके आदेश में शामिल है",
//           "items which required doctor’s prescription":
//               "जिन वस्तुओं के लिए डॉक्टर के नुस्खे की आवश्यकता होती है",
//           "Delivery Type": "वितरण के प्रकार",
//           "Self Pickup": "स्व चयन",
//           "Delivery": "वितरण",
//           "Wallet information": "बटुआ जानकारी",
//           "Recharge": "फिर से दाम लगाना",
//           "Balance": "संतुलन",
//           "Apply Coupon": "कूपन के लिए आवेदन करो",
//           "Use code:": "कोड का प्रयोग करें:",
//           "Remove": "निकालना",
//           "Apply": "आवेदन करना",
//           "View all coupons": "सभी कूपन देखें",
//           "Bill details": "बिल विवरण",
//           "Cart total": "कुल गाड़ी",
//           "Store Charge": "स्टोर चार्ज",
//           "Coupon": "कूपन",
//           "Delivery Fee": "वितरण शुल्क",
//           "To pay": "भुगतान करने के लिए",
//           "View Detailed Bill": "विस्तृत विधेयक देखें",
//           "Please Change Address": "कृपया पता बदलें",
//           "A minimum cart total of": "न्यूनतम कार्ट कुल",
//           "is required for this order.": "इस आदेश के लिए आवश्यक है।",
//           "Medicine in your cart need a prescription":
//               "आपके कार्ट में मौजूद दवा के लिए नुस्खे की आवश्यकता होती है",
//           "Select Address": "पता चुनें",
//           "Please Select Timeslot": "कृपया समयावधि चुनें",
//           "Proceed": "आगे बढ़ना",
//           "Is's Lonely in here...": "यहाँ अकेला है...",
//           "Why don't you check some products on our \n Pharmafast":
//               "आप हमारे \n फ़ार्माफ़ास्ट पर कुछ उत्पादों की जांच क्यों नहीं करते",
//           "Explore more": "और ज्यादा खोजें",
//           "Yey! You've saved": "हाँ! आपने बचा लिया",
//           "With this coupon": "इस कूपन के साथ",
//           "Suppoting small businesses has never been so rewarding!":
//               "छोटे व्यवसायों का समर्थन करना इतना फायदेमंद कभी नहीं रहा!",
//           "Awesome!": "बहुत बढ़िया!",
//           "Choose a delivery address": "एक डिलीवरी पता चुनेः",
//           "Will manage delivery and send tracking updates for the selected address":
//               "डिलीवरी का प्रबंधन करेगा और चयनित पते के लिए ट्रैकिंग अपडेट भेजेगा",
//           "Add New Address": "नया पता जोड़ें",
//           "Add Your Address": "अपना पता जोड़ें",
//           "Select delivery address": "वितरण पता चुनें",
//           "We deliver items to this address.":
//               "हम इस पते पर आइटम डिलीवर करते हैं।",
//           "The order delivery is managed by":
//               "ऑर्डर डिलीवरी द्वारा प्रबंधित किया जाता है",
//           "Orders are usually dispatched in 3 - 5 day":
//               "आदेश आमतौर पर 3 - 5 दिनों में भेज दिए जाते हैं",
//           "Pickup from Stores": "स्टोर से पिकअप",
//           "You required to collect medicine from Below address":
//               "आपको नीचे दिए गए पते से दवा लेनी है",
//           "CAMERA": "कैमरा",
//           "GALLARY": "गैलरी",
//           "Enter address details": "पता विवरण दर्ज करें",
//           "Save Address": "पता सहेजें",
//           "Near": "पास में",
//           "Complete address": "पूर्ण पता",
//           "Please enter Complete address": "कृपया पूरा पता दर्ज करें",
//           "Landmark": "सीमाचिह्न",
//           "Please enter Landmark": "कृपया मील का पत्थर दर्ज करें",
//           "How to reach instructions (Optional)":
//               "निर्देश कैसे प्राप्त करें (वैकल्पिक)",
//           "Save address as": "पता इस रूप में सहेजें",
//           "Eg: Home, Store": "जैसे: घर, स्टोर",
//           "Please enter save address as":
//               "कृपया पता इस रूप में सहेजें दर्ज करें",
//           "Search for your delivery address": "अपना डिलीवरी पता खोजें",
//           "Add Your delivery address": "अपना वितरण पता जोड़ें",
//           "Get current location with GPS":
//               "जीपीएस के साथ वर्तमान स्थान प्राप्त करें",
//           "Select & Proceed": "चयन करें और आगे बढ़ें",
//           "PharmaFast": "फार्माफास्ट",
//           "Medicine Solution": "औषधि समाधान",
//           "Sign in !": "दाखिल करना !",
//           "Welcome back you’ve been missed! ": "आपका स्वागत है आप चूक गए हैं!",
//           "Mobile Number": "मोबाइल नंबर",
//           "Please enter your mobile number": "अपना मोबाइल नंबर दर्ज करें",
//           "Please enter your password": "अपना पासवर्ड दर्ज करें",
//           "Password": "पासवर्ड",
//           "Remember me": "पहचाना की नहीं",
//           "Forgot Password?": "पासवर्ड भूल गए?",
//           "Don't have an account?": "खाता नहीं है?",
//           "Sign Up": "साइन अप करें",
//           "Verification Code": "सत्यापन कोड",
//           "We have sent the code verification to":
//               "हमने कोड सत्यापन को भेज दिया है",
//           "Please enter your otp": "कृपया अपना ओटीपी दर्ज करें",
//           "Didn't receive code?": "कोड नहीं मिला?",
//           "Resend New Code": "नया कोड पुनः भेजें",
//           "Verify": "सत्यापित करना",
//           "Please enter your valid OTP": "कृपया अपना वैध ओटीपी दर्ज करें",
//           "Forgot Password": "पासवर्ड भूल गए",
//           "Create Your New Password": "अपना नया पासवर्ड बनाएं",
//           "Conform Password": "पासवर्ड अनुरूप करें",
//           "Please Enter Valid Password": "कृपया मान्य पासवर्ड दर्ज करें",
//           "Reset Password": "पासवर्ड रीसेट",
//           "Please enter your phone number to request a\npassword reset":
//               "पासवर्ड रीसेट करने का\nअनुरोध करने के लिए कृपया अपना फोन नंबर दर्ज करें",
//           "Please enter your number": "कृपया अपना नंबर दर्ज करें",
//           "Request OTP": "ओटीपी का अनुरोध करें",
//           "You remember your password?": "आपको अपना पासवर्ड याद है?",
//           "Log In": "लॉग इन करें",
//           "Sign Up !": "साइन अप करें !",
//           "Create an account to continue.": "जारी रखने के लिए एक खाता बनाएँ।",
//           "Please enter your name": "कृपया अपना नाम दर्ज करें",
//           "Email Address": "मेल पता",
//           "Please enter your email": "अपना ईमेल दर्ज करें",
//           "Referral code (optional)": "रेफ़रल कोड (वैकल्पिक)",
//           "By creating an account,you agree to our":
//               "एक खाता बनाकर, आप हमारी सहमति देते हैं",
//           "Terms and Condition": "नियम व शर्तें",
//           "Please select Terms and Condition": "कृपया नियम और शर्त चुनें",
//           "Already have an account?": "क्या आपके पास पहले से एक खाता मौजूद है?",
//           "Login": "लॉग इन करें",
//           "Current Order": "अभी का ऑर्डर",
//           "Past Orders": "पिछले आदेश",
//           "Info": "जानकारी",
//           "No orders placed!": "कोई आदेश नहीं दिया!",
//           "Currently you don’t have any orders.":
//               "वर्तमान में आपके पास कोई आदेश नहीं है।",
//           "Select Reason": "कारण चुनें",
//           "Please select the reason for cancellation:":
//               "कृपया रद्द करने का कारण चुनें:",
//           "Confirm": "पुष्टि करना",
//           "Order ID:": "आदेश कामतत्व:",
//           "Uploaded Prescription": "अपलोड किया गया नुस्खा",
//           "Medicine information": "दवा की जानकारी",
//           "Total Item": "कुल वस्तु",
//           "Note": "टिप्पणी",
//           "Payment Information": "भुगतान जानकारी",
//           "Status": "दर्जा",
//           "Order Type": "आदेश प्रकार",
//           "Time Slot": "टाइम स्लॉट",
//           "Payment Method": "भुगतान विधि",
//           "Transaction ID": "लेन-देन आईडी",
//           "Order Date": "आर्डर की तारीख",
//           "Sub total": "उप कुल",
//           "Coupons": "कूपन",
//           "Delivery Charge": "वितरण शुल्क",
//           "Tax": "कर",
//           "Total Amount": "कुल राशि",
//           "Delivery Address": "डिलिवरी का पता",
//           "Store Details": "स्टोर विवरण",
//           "Delivery Boy Details": "डिलीवरी बॉय विवरण",
//           "Leave a Review": "समीक्षा लिखें",
//           "How was your experience": "आपका अनुभव कैसा रहा",
//           "Write Your Review": "अपना आलेख लिखो",
//           "Your review here...": "यहां आपकी समीक्षा...",
//           "Maybe Later": "शायद बाद में",
//           "Submit": "जमा करना",
//           "Please don`t press back until the transaction is complete":
//               "लेन-देन पूरा होने तक कृपया वापस न दबाएं",
//           "My Prescription Order": "मेरा नुस्खा आदेश",
//           "View Cart": "टोकरी देखें",
//           "Reject": "अस्वीकार करना",
//           "Accept": "स्वीकार करना",
//           "Upload and Proceed": "अपलोड करें और आगे बढ़ें",
//           "What is a valid Prescription ?": "एक वैध नुस्खा क्या है?",
//           "How prescription process work":
//               "नुस्खे की प्रक्रिया कैसे काम करती है",
//           "Easy & Fast Process": "आसान और तेज़ प्रक्रिया",
//           "Excusive Support": "विशेष समर्थन",
//           "Delivery Doorstep": "डिलीवरी डोरस्टेप",
//           "FAQ": "सामान्य प्रश्न",
//           "Enter reason": "कारण दर्ज करें",
//           "Doctor Name and Signature": "डॉक्टर का नाम और हस्ताक्षर",
//           "Patient Name": "रोगी का नाम",
//           "Date of Prescription": "नुस्खे की तारीख",
//           "Order Placed Successfully!": "आदेश सफलतापूर्वक दिया गया!",
//           "Don't crop out any part of the image":
//               "छवि के किसी भी हिस्से को काट-छाँट न करें",
//           "Avoid blurred image": "धुंधली छवि से बचें",
//           "Include Details of doctor and patient + clinic visit date":
//               "डॉक्टर और रोगी का विवरण + क्लिनिक विज़िट की तारीख शामिल करें",
//           "Medicines will be dispensed as per prescription":
//               "डॉक्टर के पर्चे के अनुसार दवाएं दी जाएंगी",
//           "View Sample Prescription": "नमूना नुस्खा देखें",
//           "Thank you for your order! Our team is \n working hard to package and ship your \n items as soon as possible.":
//               "आपके ऑर्डर के लिए धन्यवाद! हमारी टीम आपके \n आइटम को जल्द से जल्द पैकेज और शिप करने के लिए कड़ी मेहनत कर रही है।",
//           "Home": "घर",
//           "Refer a Friend": "एक मित्र को सूचित करें",
//           "Your prescription was uploaded and sent successfully":
//               "आपका नुस्खा अपलोड कर दिया गया और सफलतापूर्वक भेज दिया गया",
//           "Once the store processes your order,\n your cart will be ready for checkout.":
//               "एक बार जब स्टोर आपका ऑर्डर प्रोसेस कर लेता है,\n आपका कार्ट चेकआउट के लिए तैयार हो जाएगा।",
//           "Please Upload Prescription": "प्लीज अपलोड प्रिस्क्रिप्शन",
//           "Love This": "इसे प्रेम करें",
//           "Love this": "इसे प्रेम करें",
//         },
//         'ar_US': {
//           "Pharmafast": "Pharmafast",
//         },
//         'fr_US': {
//           "Pharmafast": "Pharmafast",
//         },
//         'de_US': {
//           "Pharmafast": "Pharmafast",
//         },
//         'in_US': {
//           "Pharmafast": "Pharmafast",
//         },
//         'pt_US': {
//           "Pharmafast": "Pharmafast",
//         },
//         'ZA_US': {
//           "Pharmafast": "Pharmafast",
//         },
//         'es_US': {
//           "Pharmafast": "Pharmafast",
//         },
//         'tr_US': {
//           "Pharmafast": "Pharmafast",
//         }
//       };
// }
